version: "3.7"
services:
  php1:
    container_name: leverage-lambda-skeleton-php
    image: architechlabs/php
    user: ${UID}:${GID}
    env_file:
      - .env
    networks:
      foo-net:
        ipv4_address: 192.168.112.3
    volumes:
      - .:/app
      - ~/.ssh:/home/dev/.ssh

  web:
      image: bref/fpm-dev-gateway
      ports:
        - '8000:80'
      volumes:
        - .:/var/task
      depends_on:
        - php
      networks:
        foo-net:
          ipv4_address: 192.168.112.4
      environment:
        HANDLER: index.php

  php:
    image: bref/php-81-fpm-dev
    networks:
      foo-net:
        ipv4_address: 192.168.112.5
    volumes:
      - .:/var/task:ro

  serverless:
    build:
      context: docker/serverless
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      foo-net:
        ipv4_address: 192.168.112.2


networks:
  foo-net:
    name: foo-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.112.0/24