service: app

custom:
    serverless-offline:
        host: 0.0.0.0
        useDocker: true
        dockerHost: host.docker.internal

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref
    - serverless-offline

functions:
    hello:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-81}

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'